[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
flate2 = { version = "1.1", default-features = false, features = ["rust_backend"] }
serde_json.workspace = true
zip = { version = "2.4.2", default-features = false, features = ["deflate-flate2", "flate2"] }

[dev-dependencies]
tempfile = "3.20"
