pub mod browser;
pub mod capture;
pub mod command;
pub mod config;
pub mod config_store;
pub mod error;
pub mod hotkey;
pub mod provider;
pub mod request;
pub mod state;
pub mod workflow;

pub use browser::{BrowserTarget, FocusEvidence, TargetDecision, TargetResolver};
pub use capture::{CapturedImage, ScreenRect};
pub use command::AppCommand;
pub use config::{AppConfig, BrowserConfig, BrowserTargetPreference, GeneralConfig, HotkeyConfig};
pub use config_store::{ConfigLoad, ConfigStore};
pub use error::{AppError, Result};
pub use hotkey::{HotkeyBinding, HotkeyValidationError, ModifierKey, VirtualKey};
pub use provider::{ProviderConfig, ProviderOverride};
pub use request::{DispatchMode, DispatchRequest};
pub use state::AppState;
pub use workflow::WorkflowController;
